for d2f

diff --git a/bin/d2f b/bin/d2f
--- a/bin/d2f
+++ b/bin/d2f
@@ -1,19 +1,25 @@
-#!/bin/bash
-# convert a .drawio diagram into a factbase
+# #!/bin/bash
+# # convert a .drawio diagram into a factbase
 
-set -e
-trap 'catch' ERR
+# set -e
+# trap 'catch' ERR
 
-catch () {
-    echo '*** FATAL ERROR in transpile.bash ***' 1>&2
-    exit 1
-}
+# catch () {
+#     echo '*** FATAL ERROR in transpile.bash ***' 1>&2
+#     exit 1
+# }
 
-#!/bin/bash
-d2fdir=~/quicklisp/local-projects/d2f
-dpfr $1.drawio drawio.ohm drawio.glue d2fsupport.js \
-    | pfr - $d2fdir/diagram.ohm $d2fdir/diagram.glue $d2fdir/d2fsupport.js \
-    | pfr - $d2fdir/styleexpander.ohm $d2fdir/styleexpander.glue $d2fdir/d2fsupport.js \
-    | pfr - $d2fdir/factbase.ohm $d2fdir/factbase.glue $d2fdir/d2fsupport.js \
-    | sed -E -e 's/</\n</g' \
-    | sort
+# #!/bin/bash
+# temp=`which pfrs`
+# appdir=`dirname ${temp}`/d2fapp
+# cd ${appdir}
+# pfrs $1 drawio.ohm  drawio.glue  d2fsupport.js \
+#      | pfrs - diagram.ohm diagram.glue  d2fsupport.js \
+#      | pfrs - styleexpander.ohm styleexpander.glue  d2fsupport.js \
+#      | pfrs - factbase.ohm factbase.glue  d2fsupport.js \
+#      | sed -E -e 's/</\n</g' \
+#      | sort \
+#      | sed -E -e '/^[ \t]*$/d'
+
+
+d2fpfrs.bash helloworld.drawio drawio.ohm drawio.glue d2fsupport.js
